name: Run NUnit Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up .NET environment
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    # Step 3: Clean and rebuild the solution
    - name: Clean and rebuild solution
      run: |
        dotnet clean TestAssignment322/TestAssignment322.sln
        dotnet build TestAssignment322/TestAssignment322.sln --configuration Release

    # Step 4: Run NUnit tests
    - name: Run NUnit Tests
      run: dotnet test TestAssignment322/TestAssignment322.sln --configuration Release --logger "trx;LogFileName=test_results.trx" --framework net8.0 --arch x64
