name: Run NUnit Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up .NET environment
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: dotnet restore TestAssignment322/TestAssignment322.sln

    # Step 4: Build the solution
    - name: Build solution
      run: dotnet build MyConsoleApp/MyConsoleApp.sln --configuration Release

    # Step 5: Run NUnit tests
    - name: Run NUnit Tests
      run: dotnet test MyConsoleApp/MyConsoleApp.sln --configuration Release --logger "trx;LogFileName=test_results.trx"

    # Step 6: Upload test results
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/*.trx'
